play_motion:
  motions:
    torso_up:
      joints: [torso_lift_joint]
      points:
      - positions: [0.34]
        time_from_start: 1.0

    look_down:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.0, -0.6]
        time_from_start: 1.0

